compressionLevel: mixed
enableGlobalCache: true
nmHoistingLimits: workspaces
nodeLinker: node-modules

injectEnvironmentFiles:
  - .env?

npmScopes:
  d11:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_PAT:-'dummy'}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
