name: Monitor Open Issues
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 0 * * *'
env:
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios @slack/web-api --legacy-peer-deps

      - name: Run script
        run: node .github/scripts/monitor-issues.js $GIT_SECRET $SLACK_BOT_TOKEN $SLACK_CHANNEL
